### PR TITLE
Possibility to include validators

### PR DESCRIPTION
**Pull request by rigal-m**
Possibility to include validators as follow:

```yaml
# [schema.yaml]
key: include('my_validator')

---
my_validator: map(int(), num())
```

Validators can be included inside list/map/any objects, but can't be defined recursively.

### CODE REVIEW

**Comment by rigal-m** [comment]
Hi @blopker, I have finished to implement the new functionality and did a PR. Please let me know if something isn't alright and feel free to edit what I did!

**Comment by blopker** [comment]
Very cool. I'll check it out this week.

You should rebase off the current Yamale master. It looks like the changes from the last PR are still in your branch.

**Comment by rigal-m** [comment]
Sorry for this... I just did the rebase, normally only changes from this PR should appear.

**Comment by mildebrandt** [comment]
Thanks for your submission. We decided to use the implementation from #60 for this item.

**Pull request closed without merging**
