### PR TITLE
Add validators for 'any' and 'null' types.

### PR DESCRIPTION
**Pull request by steveherrin**
Modify schema to evaluate 'any' properly. Add tests for new types.

This hopefully fits the feature suggestion in #8 .

### CODE REVIEW

**Comment by blopker** [comment]
Hey Steve, thanks for implementing `any` and `none`! 

I looked in to the way Yaml deals with non-values (Python's `None`). As you found while making the tests Yaml uses `null`. I'd rather use Yaml's nomenclature for types than Python's so can you rename the `none` validator to `null`?

I'll be able to merge this when that change lands and when I figure out why my CI isn't running :(

Cheers!

**Comment by blopker** [comment]
Oh also adding the new types to the README would be helpful too :)

**Comment by steveherrin** [comment]
Thanks for the comments, @blopker. I've renamed "none" -> "null" and updated the README.

**Comment by blopker** [comment]
Sweet, thanks. I have a few other minor changes, but I'll add them after CI is done.

**Comment by blopker** [comment]
OK, the failing test were't you fault... I'm not sure what changed since I last run them, but they're fixed now. Once https://github.com/23andMe/Yamale/pull/19 passed I'll merge.

**Pull request merged**
