### PR TITLE
Fix #106: remove Python 2 support

### LINKED ISSUE #106: Remove Python 2 support
Python 2 has been EOL for a few months now and we don't use it internally any more. Let's remove support for Python 2 and cut a new major version of Yamale. We can also enable strict mode be default at the same time.

### PR DESCRIPTION
**Pull request by blopker**
For v3.

### CODE REVIEW

**Comment by mildebrandt** [comment]
Don't forget the README.

**Comment by blopker** [comment]
Will do! What should we add?

**Comment by blopker** [comment]
Oh, I see what you mean.

**Comment by blopker** [comment]
OK, this is ready for review now.

**Pull request merged**
